### PR TITLE
Handle commented out require() correctly

### PR DESCRIPTION
**Pull request by SahAssar**
In other words don't load them.

### CODE REVIEW

**Comment by SahAssar** [comment]
This also fixes when a dependency uses require() in a function call like [here](https://github.com/kenwheeler/slick/blob/master/slick/slick.js#L23) for example.

**Comment by Stuk** [comment]
Thanks for the PR!

Unfortunately there are a couple of issues:
* I've just [added a test for having multiple requires on one line](https://github.com/Stuk/require1k/commit/eb9bd9e2287326f34baa0f0670a768cbd5be730a), which this PR breaks
* This PR also pushes the minified size of the script over 1k, which is one of the goals of this project

If you can find a way to address these issues I would be more than happy to merge!

**Comment by Stuk** [comment]
Going to close this for now. Feel free to re-open if you can address the issues!

**Comment by SahAssar** [comment]
Yep, totally understand, I probably won't be able to fix this within the requirements (my regex abilities aren't up to fixing this but also allowing for multiple requires per line and keeping it under 1k), but this was a fun exercise nonetheless :)

**Pull request closed without merging**
