### PR TITLE
added bower.json spec

### PR DESCRIPTION
**Pull request by vivaserver**
For working with the Bower package manager. Tested and added to the Bower registry.

### CODE REVIEW

**Comment by Stuk** [comment]
Thanks! Could you update the homepage to point at http://stuk.github.io/require1k/ and add the repository property to point here?

**Comment by vivaserver** [comment]
Sure! I'll update the homepage as son as I get home (on my mobile now)

**Comment by vivaserver** [comment]
Bower spec. homepage updated as requested. I will also remove my repo. from the Bower registry so that you can add yours after merging the pull request.

**Comment by Stuk** [comment]
Cheers!

**Pull request merged**
